language: php
sudo: false

php:
    - "7.0"
    - "5.6"
    - "5.5"
    - "hhvm"

matrix:
    fast_finish: true
    allow_failures:
        - php: "hhvm"

install:
    - composer self-update
    - composer update
